### ISSUE TITLE
Can the public access master.tus.io/files to test?

### ISSUE THREAD

**Issue by andrewmclagan** [tus/tus.io#124]
Can the public access master.tus.io/files to test? the CORS policy blocks this at present. See my component:

https://beam-australia.github.io/material-tus/?path=/story/upload--events

**Comment by Acconut** [comment]
master.tus.io is configured to accept uploads from any domain for testing purposes, just as you want. I just confirmed that the CORS headers are working a indented.

However, you use https://master.tus.io/files instead of https://master.tus.io/files/ as the upload creation endpoint (notice the trailing slash). tusd will redirect you to a URL with the trailing slashes. The problem is that browsers interpret this redirect as a failed OPTIONS request causing the CORS warnings. You can see the redirect by looking into the network tab inside your developer tools.

So, it's not our CORS policy blocking you but instead a wrongly configured application.
